version: 1.0.0.{build}

#  - cinst pester -y
install:
  - ps: |
      Import-module .\tools\appveyorPhases.psm1
      Invoke-AppveyorInstall

build_script:
  - ps: |
      Import-module .\tools\appveyorPhases.psm1
      Invoke-AppveyorBuild      

# Artifacts would not be collected if build failed. To do that, we use on_finish:
#-artifacts:
#  - path: nuget\*.nupkg

on_finish:
  - ps: |
      ls .\out | % { Push-AppveyorArtifact $_.FullName }

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache
test_script:
  - ps: |
      Import-module .\tools\appveyorPhases.psm1
      Invoke-AppveyorTest
