version: 1.0.0.{build}

install:
  - ps: |
      Import-Module .\PoshBuildTools
      $moduleInfoList = New-BuildModuleInfo -Auto
      Write-verboseBuildModuleInfo -moduleInfoList $moduleInfoList
      Invoke-AppveyorInstall -skipConvertToHtmlInstall

build_script:
  - ps: |
      Import-Module .\PoshBuildTools
      Invoke-AppveyorBuild -moduleInfoList $moduleInfoList -publishModule  

# Artifacts would not be collected if build failed. To do that, we use on_finish:
#-artifacts:
#  - path: nuget\*.nupkg

on_finish:
  - ps: |
      Import-Module .\PoshBuildTools
      Invoke-AppveyorFinish -moduleInfoList $moduleInfoList

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache
test_script:
  - ps: |
      Import-Module .\PoshBuildTools
      Invoke-AppveyorTest -moduleInfoList $moduleInfoList 
