version: 1.0.0.{build}

install:
  - cinst pester -y
  - ps: |
      Import-module .\tools\appveyor.psm1
      Invoke-AppveyorInstall

build_script:
  - ps: |
      Import-module .\tools\appveyor.psm1
      Invoke-AppveyorBuild      

# Artifacts would not be collected if build failed. To do that, we use on_finish:
#-artifacts:
#  - path: nuget\*.nupkg

on_finish:
  - ps: |
      ls .\out | % { Push-AppveyorArtifact $_.FullName }

test_script:
  - ps: |
      Import-module .\tools\appveyor.psm1
      Invoke-AppveyorTest
